-- eon_float_sizes.lua  --  GENERATED by EON_FloatSize_Export.lua; do not hand-edit.
--
-- The floating-window size EON set for each plugin: the CANVAS, in logical
-- px at 100% display scale, with the plugin's @gfx so EON_FloatSize_Watch
-- can tell a fresh window (still at @gfx) from one somebody already sized.
-- A plugin missing here is never touched.
return {
  ["1175_ReaKit"] = { w = 545, h = 204, gfx_w = 464, gfx_h = 840 },
  ["3BandEQ_ReaKit"] = { w = 418, h = 228, gfx_w = 460, gfx_h = 900 },
  ["ChannelTool_ReaKit"] = { w = 350, h = 546, gfx_w = 450, gfx_h = 540 },
  ["DDC_ReaKit"] = { w = 573, h = 319, gfx_w = 600, gfx_h = 520 },
  ["DeEsser_ReaKit"] = { w = 465, h = 376, gfx_w = 540, gfx_h = 520 },
  ["Delay_ReaKit"] = { w = 581, h = 560, gfx_w = 620, gfx_h = 760 },
  ["EON_Drum_Strip"] = { w = 504, h = 368, gfx_w = 300, gfx_h = 700 },
  ["Gate_ReaKit"] = { w = 512, h = 430, gfx_w = 560, gfx_h = 520 },
  ["Saturation_ReaKit"] = { w = 288, h = 506, gfx_w = 220, gfx_h = 320 },
  ["StereoWidth_ReaKit"] = { w = 291, h = 364, gfx_w = 200, gfx_h = 280 },
}
