-- rk_lua_fx_recipes.lua -- GENERATED, DO NOT EDIT BY HAND.
-- Sources:    .refs/fx_picker_card_recipes.md   (card recipes)
--             .refs/fx_categories.tsv           (the hand-edited list)
-- Regenerate: python .dev_fxpicker/gen_recipe_table.py
--
-- Rung 1 of the FX Picker category ladder -- authoritative for known plugins.
-- ROWS are pre-sorted LONGEST KEY FIRST so the matcher takes the most
-- specific hit ("pro c 2" beats "pro c") with no runtime sorting.
-- PATHS is an exact-match hash on a JSFX ident, lowercased with forward
-- slashes -- a JSFX display name changes whenever its author edits the
-- desc: line, but its path does not.
-- (c) EON Studios -- All Rights Reserved

local M = {}

M.BUCKETS = { "comp", "eq", "sat", "verb", "delay", "limit", "strip", "pitch", "amp", "util", "gate", "mod", "filter", "meter", "width", "tape", "time", "clip", "bass", "de-ess", "summing", "no-guess" }
M.INSTRUMENT_BUCKETS = { "synth", "sampler", "drums", "keys", "orchestral", "world", "sfx", "midi", "other" }

-- { normalised name key, bucket, subcategory, kind, display name }
M.ROWS = {
  { "garritan abbey road studios cfx concert grand", "keys",     "",           "instrument", "Garritan Abbey Road Studios CFX Concert Grand" },
  { "abbey road one orchestral foundations", "orchestral", "",           "instrument", "Abbey Road One: Orchestral Foundations" },
  { "spotlight collection balinese gamelan", "world",    "",           "instrument", "Spotlight Collection: Balinese Gamelan" },
  { "precision k stereo ambience recovery", "width",    "",           "fx",         "Precision K-Stereo Ambience Recovery" },
  { "emt 250 classic electronic reverb", "verb",     "",           "fx",         "EMT 250 Classic Electronic Reverb" },
  { "spotlight collection middle east", "world",    "",           "instrument", "Spotlight Collection: Middle East" },
  { "spotlight collection west africa", "world",    "",           "instrument", "Spotlight Collection: West Africa" },
  { "bbc symphony orchestra discover", "orchestral", "",           "instrument", "BBC Symphony Orchestra Discover" },
  { "tr 707 software rhythm composer", "drums",    "",           "instrument", "TR-707 Software Rhythm Composer" },
  { "tr 808 software rhythm composer", "drums",    "",           "instrument", "TR-808 Software Rhythm Composer" },
  { "tr 909 software rhythm composer", "drums",    "",           "instrument", "TR-909 Software Rhythm Composer" },
  { "abbey road tg mastering chain", "strip",    "",           "fx",         "Abbey Road TG Mastering Chain" },
  { "blue cat s oscilloscope multi", "meter",    "",           "fx",         "Blue Cat's Oscilloscope Multi" },
  { "chandler limited curve bender", "eq",       "",           "fx",         "Chandler Limited Curve Bender" },
  { "aphex vintage aural exciter",   "sat",      "exciter",    "fx",         "Aphex Vintage Aural Exciter" },
  { "dytronics tri stereo chorus",   "mod",      "",           "fx",         "Dytronics Tri-Stereo Chorus" },
  { "f6 floating band dynamic eq",   "eq",       "dynamic",    "fx",         "F6 Floating-Band Dynamic EQ" },
  { "korg sdd 3000 digital delay",   "delay",    "",           "fx",         "Korg SDD-3000 Digital Delay" },
  { "blue cat s stereoscope pro",    "meter",    "phase",      "fx",         "Blue Cat's StereoScope Pro" },
  { "spotlight collection india",    "world",    "",           "instrument", "Spotlight Collection: India" },
  { "thermionic culture vulture",    "sat",      "tube",       "fx",         "Thermionic Culture Vulture" },
  { "virtual console collection",    "sat",      "",           "fx",         "Virtual Console Collection" },
  { "audiorealism drum machine",     "drums",    "",           "instrument", "AudioRealism Drum Machine" },
  { "leslie 122 rotary speaker",     "mod",      "",           "fx",         "Leslie 122 Rotary Speaker" },
  { "scheps parallel particles",     "sat",      "",           "fx",         "Scheps Parallel Particles" },
  { "spotlight collection cuba",     "world",    "",           "instrument", "Spotlight Collection: Cuba" },
  { "cinematic studio strings",      "orchestral", "",           "instrument", "Cinematic Studio Strings" },
  { "spitfire chamber strings",      "orchestral", "",           "instrument", "Spitfire Chamber Strings" },
  { "the orchestra complete 3",      "orchestral", "",           "instrument", "The Orchestra Complete 3" },
  { "youlean loudness meter 2",      "meter",    "loudness",   "fx",         "Youlean Loudness Meter 2" },
  { "blue cat s late replies",       "delay",    "",           "fx",         "Blue Cat's Late Replies" },
  { "era ii medieval legends",       "world",    "",           "instrument", "ERA II Medieval Legends" },
  { "fix flanger and doubler",       "mod",      "",           "fx",         "Fix Flanger and Doubler" },
  { "miroslav philharmonik 2",       "orchestral", "",           "instrument", "Miroslav Philharmonik 2" },
  { "primary source expander",       "gate",     "",           "fx",         "Primary Source Expander" },
  { "tonal balance control 2",       "meter",    "",           "fx",         "Tonal Balance Control 2" },
  { "tx16wx software sampler",       "sampler",  "",           "instrument", "TX16Wx Software Sampler" },
  { "ventus winds shakuhachi",       "world",    "",           "instrument", "Ventus Winds - Shakuhachi" },
  { "wlm plus loudness meter",       "meter",    "loudness",   "fx",         "WLM Plus Loudness Meter" },
  { "abbey road 60s drummer",        "drums",    "",           "instrument", "Abbey Road 60s Drummer" },
  { "blue cat s freqanalyst",        "meter",    "spectrum",   "fx",         "Blue Cat's FreqAnalyst" },
  { "cooper time cube mk ii",        "delay",    "",           "fx",         "Cooper Time Cube MK II" },
  { "ethno world 6 complete",        "world",    "",           "instrument", "Ethno World 6 Complete" },
  { "hans zimmer percussion",        "drums",    "",           "instrument", "Hans Zimmer Percussion" },
  { "olafur arnalds stratus",        "keys",     "",           "instrument", "Olafur Arnalds Stratus" },
  { "ovox vocal resynthesis",        "pitch",    "",           "fx",         "OVox Vocal ReSynthesis" },
  { "shadow hills mastering",        "comp",     "",           "fx",         "Shadow Hills Mastering" },
  { "steven slate drums 5 5",        "drums",    "",           "instrument", "Steven Slate Drums 5.5" },
  { "valhallaspacemodulator",        "mod",      "",           "fx",         "ValhallaSpaceModulator" },
  { "vitamin sonic enhancer",        "sat",      "",           "fx",         "Vitamin Sonic Enhancer" },
  { "4u meter fader ms pan",         "meter",    "",           "fx",         "4U Meter, Fader & MS-Pan" },
  { "blue cat s destructor",         "amp",      "cabinet",    "fx",         "Blue Cat's Destructor" },
  { "bx console ssl 4000 e",         "strip",    "",           "fx",         "bx_console SSL 4000 E" },
  { "dragonfly hall reverb",         "verb",     "hall",       "fx",         "Dragonfly Hall Reverb" },
  { "fortin nameless suite",         "amp",      "",           "fx",         "Fortin Nameless Suite" },
  { "instant flanger mk ii",         "mod",      "",           "fx",         "Instant Flanger Mk II" },
  { "ivory ii grand pianos",         "keys",     "",           "instrument", "Ivory II Grand Pianos" },
  { "nls non linear summer",         "sat",      "",           "fx",         "NLS Non-Linear Summer" },
  { "symphonic destruction",         "sfx",      "",           "instrument", "Symphonic Destruction" },
  { "torpedo wall of sound",         "amp",      "cabinet",    "fx",         "Torpedo Wall of Sound" },
  { "valhalla supermassive",         "verb",     "",           "fx",         "Valhalla Supermassive" },
  { "virtual tape machines",         "tape",     "",           "fx",         "Virtual Tape Machines" },
  { "blue cat s patchwork",          "util",     "routing",    "fx",         "Blue Cat's PatchWork" },
  { "brigade chorus pedal",          "mod",      "",           "fx",         "Brigade Chorus Pedal" },
  { "clariphonic dsp mkii",          "eq",       "",           "fx",         "Clariphonic DSP MkII" },
  { "instant phaser mk ii",          "mod",      "",           "fx",         "Instant Phaser Mk II" },
  { "lindell 902 de esser",          "de-ess",   "",           "fx",         "Lindell 902 De-Esser" },
  { "notjustanotherdither",          "util",     "dither",     "fx",         "NotJustAnotherDither" },
  { "ns1 noise suppressor",          "util",     "",           "fx",         "NS1 Noise Suppressor" },
  { "precision time align",          "util",     "",           "fx",         "Precision Time Align" },
  { "rx 11 voice de noise",          "util",     "",           "fx",         "RX 11 Voice De-noise" },
  { "ventus winds bansuri",          "world",    "",           "instrument", "Ventus Winds - Bansuri" },
  { "waves tune real time",          "pitch",    "",           "fx",         "Waves Tune Real-Time" },
  { "world percussion 2 0",          "world",    "",           "instrument", "World Percussion 2.0" },
  { "abbey road chambers",           "verb",     "room",       "fx",         "Abbey Road Chambers" },
  { "ample ethno ukulele",           "world",    "",           "instrument", "Ample Ethno Ukulele" },
  { "beatbox anthology 2",           "drums",    "",           "instrument", "Beatbox Anthology 2" },
  { "filtershaper core 2",           "filter",   "",           "fx",         "FilterShaper Core 2" },
  { "mt power drum kit 2",           "drums",    "",           "instrument", "MT Power Drum Kit 2" },
  { "nx virtual mix room",           "util",     "monitoring", "fx",         "Nx Virtual Mix Room" },
  { "oxide tape recorder",           "tape",     "",           "fx",         "Oxide Tape Recorder" },
  { "scheps omni channel",           "strip",    "",           "fx",         "Scheps Omni Channel" },
  { "ssl channel strip 2",           "strip",    "",           "fx",         "SSL Channel Strip 2" },
  { "tape 201 space echo",           "delay",    "",           "fx",         "TAPE-201 / Space Echo" },
  { "valhallavintageverb",           "verb",     "",           "fx",         "ValhallaVintageVerb" },
  { "ams rmx16 expanded",            "verb",     "",           "fx",         "AMS RMX16 Expanded" },
  { "dimension expander",            "width",    "",           "fx",         "Dimension Expander" },
  { "harmony engine evo",            "pitch",    "",           "fx",         "Harmony Engine Evo" },
  { "joshua bell violin",            "orchestral", "",           "instrument", "Joshua Bell Violin" },
  { "kramer hls channel",            "strip",    "",           "fx",         "Kramer HLS Channel" },
  { "kramer master tape",            "tape",     "",           "fx",         "Kramer Master Tape" },
  { "lounge lizard ep 4",            "keys",     "",           "instrument", "Lounge Lizard EP-4" },
  { "ozone 11 maximizer",            "limit",    "",           "fx",         "Ozone 11 Maximizer" },
  { "parallel aggressor",            "sat",      "",           "fx",         "Parallel Aggressor" },
  { "psp 608 multidelay",            "delay",    "",           "fx",         "PSP 608 MultiDelay" },
  { "roland dimension d",            "mod",      "",           "fx",         "Roland Dimension D" },
  { "superior drummer 3",            "drums",    "",           "instrument", "Superior Drummer 3" },
  { "ventus winds duduk",            "world",    "",           "instrument", "Ventus Winds - Duduk" },
  { "verbsuite classics",            "verb",     "",           "fx",         "VerbSuite Classics" },
  { "addictive drums 2",             "drums",    "",           "instrument", "Addictive Drums 2" },
  { "eq curve analyzer",             "meter",    "spectrum",   "fx",         "EQ Curve Analyzer" },
  { "hollywood strings",             "orchestral", "",           "instrument", "Hollywood Strings" },
  { "l1 ultramaximizer",             "limit",    "",           "fx",         "L1 Ultramaximizer" },
  { "mloudnessanalyzer",             "meter",    "spectrum",   "fx",         "MLoudnessAnalyzer" },
  { "mt powerdrumkit 2",             "drums",    "",           "instrument", "MT-PowerDrumKit 2" },
  { "oxford envolution",             "comp",     "",           "fx",         "Oxford Envolution" },
  { "ps22 stereo maker",             "width",    "",           "fx",         "PS22 Stereo Maker" },
  { "purple audio mc77",             "comp",     "fet",        "fx",         "Purple Audio MC77" },
  { "rc 20 retro color",             "tape",     "",           "fx",         "RC-20 Retro Color" },
  { "sketchcassette ii",             "tape",     "",           "fx",         "SketchCassette II" },
  { "soundid reference",             "util",     "monitoring", "fx",         "SoundID Reference" },
  { "vox continental v",             "keys",     "",           "instrument", "Vox Continental V" },
  { "world instruments",             "world",    "",           "instrument", "World Instruments" },
  { "canopener studio",              "util",     "monitoring", "fx",         "CanOpener Studio" },
  { "capitol chambers",              "verb",     "room",       "fx",         "Capitol Chambers" },
  { "dangerous bax eq",              "eq",       "",           "fx",         "Dangerous BAX EQ" },
  { "denoiser classic",              "util",     "",           "fx",         "Denoiser Classic" },
  { "devil loc deluxe",              "comp",     "",           "fx",         "Devil-Loc Deluxe" },
  { "galaxy tape echo",              "delay",    "tape",       "fx",         "Galaxy Tape Echo" },
  { "metropolis ark 1",              "orchestral", "",           "instrument", "Metropolis Ark 1" },
  { "oxford drum gate",              "gate",     "",           "fx",         "Oxford Drum Gate" },
  { "oxford supresser",              "de-ess",   "",           "fx",         "Oxford SuprEsser" },
  { "s1 stereo imager",              "width",    "",           "fx",         "S1 Stereo Imager" },
  { "transient master",              "util",     "",           "fx",         "Transient Master" },
  { "valhallafreqecho",              "delay",    "",           "fx",         "ValhallaFreqEcho" },
  { "virtual mix rack",              "strip",    "",           "fx",         "Virtual Mix Rack" },
  { "a1stereocontrol",               "width",    "",           "fx",         "A1StereoControl" },
  { "albion v tundra",               "orchestral", "",           "instrument", "Albion V Tundra" },
  { "bx saturator v2",               "sat",      "",           "fx",         "bx_saturator V2" },
  { "chow tape model",               "tape",     "",           "fx",         "Chow Tape Model" },
  { "cinematic rooms",               "verb",     "",           "fx",         "Cinematic Rooms" },
  { "console7channel",               "sat",      "",           "fx",         "Console7Channel" },
  { "cremona quartet",               "orchestral", "",           "instrument", "Cremona Quartet" },
  { "elysia karacter",               "sat",      "",           "fx",         "elysia karacter" },
  { "elysia mpressor",               "comp",     "",           "fx",         "elysia mpressor" },
  { "eq65 filter set",               "filter",   "",           "fx",         "EQ65 Filter Set" },
  { "fog convolver 2",               "verb",     "convolution", "fx",         "Fog Convolver 2" },
  { "h910 harmonizer",               "pitch",    "",           "fx",         "H910 Harmonizer" },
  { "keyzone classic",               "keys",     "",           "instrument", "Keyzone Classic" },
  { "little alterboy",               "pitch",    "",           "fx",         "Little AlterBoy" },
  { "little labs ibp",               "util",     "",           "fx",         "Little Labs IBP" },
  { "lustrous plates",               "verb",     "plate",      "fx",         "Lustrous Plates" },
  { "massive passive",               "eq",       "",           "fx",         "Massive Passive" },
  { "mstereoexpander",               "width",    "",           "fx",         "MStereoExpander" },
  { "oxford inflator",               "limit",    "",           "fx",         "Oxford Inflator" },
  { "prs supermodels",               "amp",      "",           "fx",         "PRS SuperModels" },
  { "ravenscroft 275",               "keys",     "",           "instrument", "Ravenscroft 275" },
  { "rx 11 de reverb",               "util",     "",           "fx",         "RX 11 De-reverb" },
  { "saturation knob",               "sat",      "",           "fx",         "Saturation Knob" },
  { "shortcircuit xt",               "sampler",  "",           "instrument", "Shortcircuit XT" },
  { "smooth operator",               "eq",       "",           "fx",         "Smooth Operator" },
  { "stealth limiter",               "limit",    "",           "fx",         "Stealth Limiter" },
  { "studio d chorus",               "mod",      "",           "fx",         "Studio D Chorus" },
  { "supercharger gt",               "comp",     "",           "fx",         "Supercharger GT" },
  { "supertone clear",               "util",     "",           "fx",         "Supertone Clear" },
  { "synchron player",               "sampler",  "",           "instrument", "Synchron Player" },
  { "synthmaster one",               "synth",    "",           "instrument", "SynthMaster One" },
  { "tdr vos slickeq",               "eq",       "",           "fx",         "TDR VOS SlickEQ" },
  { "thrillseekerxtc",               "sat",      "exciter",    "fx",         "ThrillseekerXTC" },
  { "trident a range",               "eq",       "",           "fx",         "Trident A-Range" },
  { "tube tech cl 1b",               "comp",     "",           "fx",         "Tube-Tech CL 1B" },
  { "uvi workstation",               "sampler",  "",           "instrument", "UVI Workstation" },
  { "valhallashimmer",               "verb",     "",           "fx",         "ValhallaShimmer" },
  { "vitalizer mk2 t",               "eq",       "",           "fx",         "Vitalizer MK2-T" },
  { "action strikes",                "drums",    "",           "instrument", "Action Strikes" },
  { "addictive keys",                "keys",     "",           "instrument", "Addictive Keys" },
  { "arturia fet 76",                "comp",     "",           "fx",         "Arturia FET-76" },
  { "beatmaker dope",                "drums",    "",           "instrument", "Beatmaker DOPE" },
  { "beatmaker hype",                "drums",    "",           "instrument", "Beatmaker HYPE" },
  { "bx stereomaker",                "width",    "",           "fx",         "bx_stereomaker" },
  { "cinebrass core",                "orchestral", "",           "instrument", "CineBrass Core" },
  { "decent sampler",                "sampler",  "",           "instrument", "Decent Sampler" },
  { "elysia nvelope",                "comp",     "",           "fx",         "elysia nvelope" },
  { "ethereal earth",                "sfx",      "",           "instrument", "Ethereal Earth" },
  { "ferrictds mkii",                "tape",     "",           "fx",         "FerricTDS mkII" },
  { "filterstation2",                "filter",   "",           "fx",         "Filterstation2" },
  { "formant filter",                "filter",   "",           "fx",         "Formant Filter" },
  { "groove agent 5",                "drums",    "",           "instrument", "Groove Agent 5" },
  { "halion sonic 7",                "sampler",  "",           "instrument", "HALion Sonic 7" },
  { "helios type 69",                "eq",       "",           "fx",         "Helios Type 69" },
  { "mautodynamiceq",                "eq",       "dynamic",    "fx",         "MAutoDynamicEq" },
  { "mconvolutionez",                "verb",     "convolution", "fx",         "MConvolutionEZ" },
  { "mmultianalyzer",                "meter",    "spectrum",   "fx",         "MMultiAnalyzer" },
  { "oxford limiter",                "limit",    "",           "fx",         "Oxford Limiter" },
  { "phaser bi tron",                "mod",      "",           "fx",         "Phaser BI-TRON" },
  { "reacontrolmidi",                "util",     "",           "fx",         "ReaControlMIDI" },
  { "reasurroundpan",                "util",     "",           "fx",         "ReaSurroundPan" },
  { "repeater delay",                "delay",    "",           "fx",         "Repeater Delay" },
  { "rotary cls 222",                "mod",      "",           "fx",         "Rotary CLS-222" },
  { "scarbee mark i",                "keys",     "",           "instrument", "Scarbee Mark I" },
  { "seventh heaven",                "verb",     "",           "fx",         "Seventh Heaven" },
  { "solid bus comp",                "comp",     "",           "fx",         "Solid Bus Comp" },
  { "ssl bus comp 2",                "comp",     "",           "fx",         "SSL Bus Comp 2" },
  { "studio drummer",                "drums",    "",           "instrument", "Studio Drummer" },
  { "stutter edit 2",                "time",     "",           "fx",         "Stutter Edit 2" },
  { "t de esser pro",                "de-ess",   "",           "fx",         "T-De-Esser Pro" },
  { "tal noisemaker",                "synth",    "",           "instrument", "TAL-NoiseMaker" },
  { "tdr kotelnikov",                "comp",     "",           "fx",         "TDR Kotelnikov" },
  { "vintagewarmer2",                "sat",      "",           "fx",         "VintageWarmer2" },
  { "808 studio ii",                 "drums",    "",           "instrument", "808 Studio II" },
  { "alicia s keys",                 "keys",     "",           "instrument", "Alicia's Keys" },
  { "ampex atr 102",                 "tape",     "",           "fx",         "Ampex ATR-102" },
  { "auto tune pro",                 "pitch",    "",           "fx",         "Auto-Tune Pro" },
  { "brauer motion",                 "mod",      "",           "fx",         "Brauer Motion" },
  { "bx control v2",                 "util",     "monitoring", "fx",         "bx_control V2" },
  { "bx digital v3",                 "eq",       "",           "fx",         "bx_digital V3" },
  { "bx masterdesk",                 "strip",    "",           "fx",         "bx_masterdesk" },
  { "chromaphone 3",                 "synth",    "",           "instrument", "Chromaphone 3" },
  { "cla 76 blacky",                 "comp",     "",           "fx",         "CLA-76 Blacky" },
  { "combo model v",                 "keys",     "",           "instrument", "Combo Model V" },
  { "dehumaniser 2",                 "sfx",      "",           "instrument", "Dehumaniser 2" },
  { "density mkiii",                 "comp",     "bus",        "fx",         "Density mkIII" },
  { "deverberate 3",                 "util",     "",           "fx",         "DeVerberate 3" },
  { "drum designer",                 "drums",    "",           "instrument", "Drum Designer" },
  { "efx fragments",                 "time",     "",           "fx",         "Efx FRAGMENTS" },
  { "emulator ii v",                 "sampler",  "",           "instrument", "Emulator II V" },
  { "fairchild 670",                 "comp",     "vari-mu",    "fx",         "Fairchild 670" },
  { "h3000 factory",                 "pitch",    "",           "fx",         "H3000 Factory" },
  { "infiltrator 2",                 "filter",   "",           "fx",         "Infiltrator 2" },
  { "kaleidoscopes",                 "mod",      "",           "fx",         "Kaleidoscopes" },
  { "kinetic metal",                 "sfx",      "",           "instrument", "Kinetic Metal" },
  { "krotos studio",                 "sfx",      "",           "instrument", "Krotos Studio" },
  { "ladder filter",                 "filter",   "",           "fx",         "Ladder Filter" },
  { "latency delay",                 "util",     "",           "fx",         "Latency Delay" },
  { "m tron pro iv",                 "sampler",  "",           "instrument", "M-Tron Pro IV" },
  { "manley voxbox",                 "strip",    "",           "fx",         "Manley VOXBOX" },
  { "niveau filter",                 "eq",       "tilt",       "fx",         "niveau filter" },
  { "phasemistress",                 "mod",      "",           "fx",         "PhaseMistress" },
  { "pitch monster",                 "pitch",    "",           "fx",         "Pitch Monster" },
  { "psp springbox",                 "verb",     "spring",     "fx",         "PSP springBox" },
  { "puigchild 670",                 "comp",     "",           "fx",         "PuigChild 670" },
  { "pultec eqp 1a",                 "eq",       "",           "fx",         "Pultec EQP-1A (any)" },
  { "rev intensity",                 "verb",     "",           "fx",         "Rev INTENSITY" },
  { "reverberate 3",                 "verb",     "convolution", "fx",         "Reverberate 3" },
  { "rough rider 3",                 "comp",     "",           "fx",         "Rough Rider 3" },
  { "scarbee a 200",                 "keys",     "",           "instrument", "Scarbee A-200" },
  { "serato sample",                 "sampler",  "",           "instrument", "Serato Sample" },
  { "shire whistle",                 "world",    "",           "instrument", "Shire Whistle" },
  { "ssl e channel",                 "eq",       "",           "fx",         "SSL E-Channel" },
  { "taiko creator",                 "world",    "",           "instrument", "Taiko Creator" },
  { "tal chorus lx",                 "mod",      "",           "fx",         "TAL-Chorus-LX" },
  { "tape mello fi",                 "tape",     "",           "fx",         "TAPE MELLO-FI" },
  { "the gentleman",                 "keys",     "",           "instrument", "The Gentleman" },
  { "the legend hz",                 "synth",    "",           "instrument", "The Legend HZ" },
  { "tricerachorus",                 "mod",      "",           "fx",         "TriceraChorus" },
  { "tsar 1 reverb",                 "verb",     "",           "fx",         "TSAR-1 Reverb" },
  { "valhalladelay",                 "delay",    "",           "fx",         "ValhallaDelay" },
  { "valhallaplate",                 "verb",     "",           "fx",         "ValhallaPlate" },
  { "vertigo vsc 2",                 "comp",     "bus",        "fx",         "Vertigo VSC-2" },
  { "vertigo vsc 3",                 "comp",     "bus",        "fx",         "Vertigo VSC-3" },
  { "vertigo vsm 3",                 "sat",      "",           "fx",         "Vertigo VSM-3" },
  { "vocal doubler",                 "width",    "",           "fx",         "Vocal Doubler" },
  { "weiss ds1 mk3",                 "limit",    "",           "fx",         "Weiss DS1-MK3" },
  { "world suite 2",                 "world",    "",           "instrument", "World Suite 2" },
  { "analog lab v",                  "synth",    "",           "instrument", "Analog Lab V" },
  { "auto align 2",                  "util",     "",           "fx",         "Auto-Align 2" },
  { "bx console n",                  "strip",    "",           "fx",         "bx_console N" },
  { "bx hybrid v2",                  "eq",       "",           "fx",         "bx_hybrid V2" },
  { "camelcrusher",                  "sat",      "",           "fx",         "CamelCrusher" },
  { "chorus jun 6",                  "mod",      "",           "fx",         "Chorus JUN-6" },
  { "cla 76 bluey",                  "comp",     "",           "fx",         "CLA-76 Bluey" },
  { "comeback kid",                  "delay",    "",           "fx",         "Comeback Kid" },
  { "convology xt",                  "verb",     "convolution", "fx",         "Convology XT" },
  { "correlometer",                  "meter",    "phase",      "fx",         "Correlometer" },
  { "crystallizer",                  "delay",    "",           "fx",         "Crystallizer" },
  { "dearvr micro",                  "width",    "",           "fx",         "dearVR MICRO" },
  { "desert winds",                  "world",    "",           "instrument", "Desert Winds" },
  { "drumcomputer",                  "drums",    "",           "instrument", "DrumComputer" },
  { "dubstation 2",                  "delay",    "",           "fx",         "Dubstation 2" },
  { "geosonics ii",                  "sfx",      "",           "instrument", "Geosonics II" },
  { "guitar rig 7",                  "amp",      "",           "fx",         "Guitar Rig 7" },
  { "hammond b 3x",                  "keys",     "",           "instrument", "Hammond B-3X" },
  { "harrison 32c",                  "eq",       "",           "fx",         "Harrison 32C" },
  { "helix native",                  "amp",      "",           "fx",         "Helix Native" },
  { "kirchhoff eq",                  "eq",       "",           "fx",         "Kirchhoff-EQ" },
  { "limiter 6 ge",                  "limit",    "",           "fx",         "Limiter 6 GE" },
  { "little plate",                  "verb",     "",           "fx",         "Little Plate" },
  { "magic switch",                  "mod",      "",           "fx",         "Magic Switch" },
  { "mstereoscope",                  "meter",    "phase",      "fx",         "MStereoScope" },
  { "mturbofilter",                  "filter",   "",           "fx",         "MTurboFilter" },
  { "omnisphere 2",                  "synth",    "",           "instrument", "Omnisphere 2" },
  { "ozone imager",                  "width",    "",           "fx",         "Ozone Imager" },
  { "panagement 2",                  "width",    "",           "fx",         "Panagement 2" },
  { "paulxstretch",                  "time",     "",           "fx",         "PaulXStretch" },
  { "paz analyzer",                  "meter",    "spectrum",   "fx",         "PAZ Analyzer" },
  { "reasurround2",                  "util",     "",           "fx",         "ReaSurround2" },
  { "reformer pro",                  "sfx",      "",           "instrument", "Reformer Pro" },
  { "retrologue 2",                  "synth",    "",           "instrument", "Retrologue 2" },
  { "sampletank 4",                  "sampler",  "",           "instrument", "SampleTank 4" },
  { "sitar nation",                  "world",    "",           "instrument", "Sitar Nation" },
  { "smack attack",                  "comp",     "",           "fx",         "Smack Attack" },
  { "soundshifter",                  "pitch",    "",           "fx",         "SoundShifter" },
  { "spl twintube",                  "sat",      "",           "fx",         "SPL TwinTube" },
  { "ssl g master",                  "comp",     "",           "fx",         "SSL G-Master (Waves)" },
  { "standardclip",                  "clip",     "",           "fx",         "StandardCLIP" },
  { "stereo touch",                  "width",    "",           "fx",         "Stereo Touch" },
  { "tal filter 2",                  "filter",   "",           "fx",         "TAL-Filter-2" },
  { "the grandeur",                  "keys",     "",           "instrument", "The Grandeur" },
  { "the maverick",                  "keys",     "",           "instrument", "The Maverick" },
  { "tone control",                  "eq",       "",           "fx",         "Tone Control" },
  { "tonelux tilt",                  "eq",       "tilt",       "fx",         "Tonelux Tilt" },
  { "trem control",                  "mod",      "",           "fx",         "Trem Control" },
  { "ultrachannel",                  "strip",    "",           "fx",         "UltraChannel" },
  { "valhallaroom",                  "verb",     "",           "fx",         "ValhallaRoom" },
  { "vocal bender",                  "pitch",    "",           "fx",         "Vocal Bender" },
  { "vocalsynth 2",                  "pitch",    "",           "fx",         "VocalSynth 2" },
  { "amplitube 5",                   "amp",      "",           "fx",         "Amplitube 5" },
  { "array mbira",                   "world",    "",           "instrument", "Array Mbira" },
  { "barricade 4",                   "limit",    "",           "fx",         "Barricade 4" },
  { "busscolors4",                   "sat",      "",           "fx",         "BussColors4" },
  { "chowcentaur",                   "amp",      "pedal",      "fx",         "ChowCentaur" },
  { "cla effects",                   "mod",      "",           "fx",         "CLA Effects" },
  { "crystalline",                   "verb",     "",           "fx",         "Crystalline" },
  { "decapitator",                   "sat",      "",           "fx",         "Decapitator" },
  { "drawmer s73",                   "comp",     "bus",        "fx",         "Drawmer S73" },
  { "element 2 0",                   "synth",    "",           "instrument", "Element 2.0" },
  { "ezdrummer 3",                   "drums",    "",           "instrument", "EZdrummer 3" },
  { "filter mini",                   "filter",   "",           "fx",         "Filter MINI" },
  { "filterfreak",                   "filter",   "",           "fx",         "FilterFreak" },
  { "filterscape",                   "filter",   "",           "fx",         "Filterscape" },
  { "filterverse",                   "filter",   "",           "fx",         "Filterverse" },
  { "infinistrip",                   "strip",    "",           "fx",         "InfiniStrip" },
  { "infinity eq",                   "eq",       "",           "fx",         "Infinity EQ" },
  { "koto nation",                   "world",    "",           "instrument", "Koto Nation" },
  { "lexicon 224",                   "verb",     "",           "fx",         "Lexicon 224" },
  { "limiter no6",                   "limit",    "",           "fx",         "Limiter No6" },
  { "mangledverb",                   "verb",     "",           "fx",         "MangledVerb" },
  { "manipulator",                   "pitch",    "",           "fx",         "Manipulator" },
  { "mastercheck",                   "meter",    "loudness",   "fx",         "MasterCheck" },
  { "mellotron v",                   "sampler",  "",           "instrument", "Mellotron V" },
  { "metaflanger",                   "mod",      "",           "fx",         "MetaFlanger" },
  { "minifreak v",                   "synth",    "",           "instrument", "MiniFreak V" },
  { "minimonsta2",                   "synth",    "",           "instrument", "Minimonsta2" },
  { "nexcellence",                   "mod",      "",           "fx",         "Nexcellence" },
  { "omnipressor",                   "comp",     "",           "fx",         "Omnipressor" },
  { "outer space",                   "delay",    "tape",       "fx",         "Outer Space" },
  { "phase plant",                   "synth",    "",           "instrument", "Phase Plant" },
  { "prophet 5 v",                   "synth",    "",           "instrument", "Prophet-5 V" },
  { "reasurround",                   "util",     "",           "fx",         "ReaSurround" },
  { "replicant 3",                   "time",     "",           "fx",         "Replicant 3" },
  { "sandman pro",                   "delay",    "",           "fx",         "Sandman Pro" },
  { "shaperbox 3",                   "mod",      "",           "fx",         "ShaperBox 3" },
  { "sine player",                   "sampler",  "",           "instrument", "SINE Player" },
  { "smart limit",                   "limit",    "",           "fx",         "smart:limit" },
  { "stereo tool",                   "width",    "",           "fx",         "Stereo Tool" },
  { "stormdrum 3",                   "drums",    "",           "instrument", "StormDrum 3" },
  { "studer a800",                   "tape",     "",           "fx",         "Studer A800" },
  { "supervision",                   "meter",    "",           "fx",         "SuperVision" },
  { "symphobia 1",                   "orchestral", "",           "instrument", "Symphobia 1" },
  { "syntronik 2",                   "synth",    "",           "instrument", "Syntronik 2" },
  { "tal sampler",                   "sampler",  "",           "instrument", "TAL-Sampler" },
  { "tal u no lx",                   "synth",    "",           "instrument", "TAL-U-NO-LX" },
  { "trackspacer",                   "comp",     "",           "fx",         "Trackspacer" },
  { "vocal rider",                   "util",     "",           "fx",         "Vocal Rider" },
  { "vos slickeq",                   "eq",       "",           "fx",         "VOS SlickEQ" },
  { "vumt deluxe",                   "meter",    "",           "fx",         "VUMT deluxe" },
  { "weiss deess",                   "de-ess",   "",           "fx",         "Weiss Deess" },
  { "wow control",                   "tape",     "",           "fx",         "Wow Control" },
  { "albion one",                    "orchestral", "",           "instrument", "Albion ONE" },
  { "altiverb 7",                    "verb",     "convolution", "fx",         "Altiverb 7" },
  { "api vision",                    "strip",    "",           "fx",         "API Vision" },
  { "bias amp 2",                    "amp",      "",           "fx",         "BIAS AMP 2" },
  { "burnley 73",                    "eq",       "",           "fx",         "Burnley 73" },
  { "capacitor2",                    "filter",   "",           "fx",         "Capacitor2" },
  { "cla mixhub",                    "strip",    "",           "fx",         "CLA MixHub" },
  { "clarity vx",                    "util",     "",           "fx",         "Clarity Vx" },
  { "compassion",                    "comp",     "",           "fx",         "Compassion" },
  { "decimort 2",                    "clip",     "",           "fx",         "Decimort 2" },
  { "equivocate",                    "eq",       "",           "fx",         "EQuivocate" },
  { "fazortan 2",                    "mod",      "",           "fx",         "Fazortan 2" },
  { "filter m12",                    "filter",   "",           "fx",         "Filter M12" },
  { "graillon 2",                    "pitch",    "",           "fx",         "Graillon 2" },
  { "gross beat",                    "time",     "",           "fx",         "Gross Beat" },
  { "marvel geq",                    "eq",       "graphic",    "fx",         "Marvel GEQ" },
  { "maschine 2",                    "drums",    "",           "instrument", "Maschine 2" },
  { "mautopitch",                    "pitch",    "",           "fx",         "MAutoPitch" },
  { "melodyne 5",                    "pitch",    "",           "fx",         "Melodyne 5" },
  { "memorymode",                    "synth",    "",           "instrument", "Memorymode" },
  { "mequalizer",                    "eq",       "",           "fx",         "MEqualizer" },
  { "metafilter",                    "filter",   "",           "fx",         "MetaFilter" },
  { "micropitch",                    "pitch",    "",           "fx",         "MicroPitch" },
  { "microshift",                    "width",    "",           "fx",         "MicroShift" },
  { "microtonic",                    "drums",    "",           "instrument", "Microtonic" },
  { "monitoring",                    "util",     "monitoring", "fx",         "Monitoring" },
  { "monofilter",                    "width",    "",           "fx",         "Monofilter" },
  { "neve 33609",                    "comp",     "bus",        "fx",         "Neve 33609" },
  { "omnisphere",                    "synth",    "",           "instrument", "Omnisphere" },
  { "organteq 2",                    "keys",     "",           "instrument", "Organteq 2" },
  { "p42 climax",                    "sat",      "exciter",    "fx",         "P42 Climax" },
  { "palindrome",                    "sfx",      "",           "instrument", "Palindrome" },
  { "pianoteq 8",                    "keys",     "",           "instrument", "Pianoteq 8" },
  { "playbeat 3",                    "drums",    "",           "instrument", "Playbeat 3" },
  { "purestgain",                    "util",     "dither",     "fx",         "PurestGain" },
  { "reaverbate",                    "verb",     "",           "fx",         "ReaVerbate" },
  { "redoptor 2",                    "sat",      "tube",       "fx",         "Redoptor 2" },
  { "replika xt",                    "delay",    "",           "fx",         "Replika XT" },
  { "smart eq 4",                    "eq",       "",           "fx",         "smart:EQ 4" },
  { "soundpaint",                    "sampler",  "",           "instrument", "Soundpaint" },
  { "spaced out",                    "verb",     "",           "fx",         "Spaced Out" },
  { "stage 73 v",                    "keys",     "",           "instrument", "Stage-73 V" },
  { "straylight",                    "sfx",      "",           "instrument", "Straylight" },
  { "studiorack",                    "util",     "routing",    "fx",         "StudioRack" },
  { "stylus rmx",                    "drums",    "",           "instrument", "Stylus RMX" },
  { "superplate",                    "verb",     "plate",      "fx",         "SuperPlate" },
  { "swarplug 4",                    "world",    "",           "instrument", "SwarPlug 4" },
  { "synplant 2",                    "synth",    "",           "instrument", "Synplant 2" },
  { "syntorus 2",                    "mod",      "",           "fx",         "Syntorus 2" },
  { "timeless 3",                    "delay",    "",           "fx",         "Timeless 3" },
  { "toraverb 2",                    "verb",     "",           "fx",         "Toraverb 2" },
  { "tremolator",                    "mod",      "",           "fx",         "Tremolator" },
  { "true level",                    "meter",    "loudness",   "fx",         "true:level" },
  { "twangstr m",                    "verb",     "spring",     "fx",         "Twangström" },
  { "uad 1176ln",                    "comp",     "",           "fx",         "UAD 1176LN" },
  { "ultrapitch",                    "pitch",    "",           "fx",         "UltraPitch" },
  { "w1 limiter",                    "limit",    "",           "fx",         "W1 Limiter" },
  { "weaponiser",                    "sfx",      "",           "instrument", "Weaponiser" },
  { "weiss mm 1",                    "limit",    "",           "fx",         "Weiss MM-1" },
  { "zebralette",                    "synth",    "",           "instrument", "Zebralette" },
  { "80 series",                     "strip",    "",           "fx",         "80 Series" },
  { "absynth 5",                     "synth",    "",           "instrument", "Absynth 5" },
  { "archetype",                     "amp",      "",           "fx",         "Archetype (Neural DSP)" },
  { "b 5 organ",                     "keys",     "",           "instrument", "B-5 Organ" },
  { "battery 4",                     "drums",    "",           "instrument", "Battery 4" },
  { "bias fx 2",                     "amp",      "",           "fx",         "BIAS FX 2" },
  { "blackhole",                     "verb",     "",           "fx",         "Blackhole" },
  { "bus force",                     "strip",    "",           "fx",         "Bus FORCE" },
  { "channel g",                     "strip",    "",           "fx",         "Channel G" },
  { "charlatan",                     "synth",    "",           "instrument", "Charlatan" },
  { "cliponly2",                     "clip",     "",           "fx",         "ClipOnly2" },
  { "denoise 2",                     "util",     "",           "fx",         "DeNoise 2" },
  { "disperser",                     "filter",   "",           "fx",         "Disperser" },
  { "djmfilter",                     "filter",   "",           "fx",         "DJMFilter" },
  { "drummic a",                     "drums",    "",           "instrument", "DrumMic'a" },
  { "drumstrip",                     "strip",    "",           "fx",         "Drumstrip" },
  { "dynameter",                     "meter",    "loudness",   "fx",         "Dynameter" },
  { "e2deesser",                     "de-ess",   "",           "fx",         "E2Deesser" },
  { "effectrix",                     "time",     "",           "fx",         "Effectrix" },
  { "farfisa v",                     "keys",     "",           "instrument", "Farfisa V" },
  { "ferrictds",                     "tape",     "",           "fx",         "FerricTDS" },
  { "fg stress",                     "comp",     "",           "fx",         "FG-Stress" },
  { "floorfish",                     "gate",     "",           "fx",         "Floorfish" },
  { "free clip",                     "clip",     "",           "fx",         "Free Clip" },
  { "fresh air",                     "sat",      "",           "fx",         "Fresh Air" },
  { "harmonics",                     "sat",      "",           "fx",         "Harmonics" },
  { "heartbeat",                     "drums",    "",           "instrument", "Heartbeat" },
  { "insight 2",                     "meter",    "",           "fx",         "Insight 2" },
  { "jupiter 8",                     "synth",    "",           "instrument", "JUPITER-8" },
  { "kontakt 8",                     "sampler",  "",           "instrument", "Kontakt 8" },
  { "landforms",                     "sfx",      "",           "instrument", "Landforms" },
  { "limitless",                     "limit",    "",           "fx",         "Limitless" },
  { "magnetite",                     "tape",     "",           "fx",         "Magnetite" },
  { "manalyzer",                     "meter",    "spectrum",   "fx",         "MAnalyzer" },
  { "massive x",                     "synth",    "",           "instrument", "Massive X" },
  { "metric ab",                     "meter",    "",           "fx",         "Metric AB" },
  { "modo drum",                     "drums",    "",           "instrument", "MODO DRUM" },
  { "morphoder",                     "pitch",    "",           "fx",         "Morphoder" },
  { "multipass",                     "util",     "",           "fx",         "Multipass" },
  { "neutron 4",                     "strip",    "",           "fx",         "Neutron 4" },
  { "neve 1073",                     "eq",       "",           "fx",         "Neve 1073 (UAD)" },
  { "neve 88rs",                     "strip",    "",           "fx",         "Neve 88RS" },
  { "orilriver",                     "verb",     "",           "fx",         "OrilRiver" },
  { "padshop 2",                     "synth",    "",           "instrument", "Padshop 2" },
  { "pan drums",                     "world",    "",           "instrument", "Pan Drums" },
  { "pendulate",                     "synth",    "",           "instrument", "Pendulate" },
  { "pharlight",                     "sfx",      "",           "instrument", "Pharlight" },
  { "piano one",                     "keys",     "",           "instrument", "Piano One" },
  { "pressure4",                     "comp",     "",           "fx",         "Pressure4" },
  { "presswerk",                     "comp",     "",           "fx",         "Presswerk" },
  { "primaltap",                     "delay",    "",           "fx",         "PrimalTap" },
  { "pulsar mu",                     "comp",     "vari-mu",    "fx",         "Pulsar Mu" },
  { "quadravox",                     "pitch",    "",           "fx",         "Quadravox" },
  { "reainsert",                     "util",     "",           "fx",         "ReaInsert" },
  { "reaninjam",                     "util",     "",           "fx",         "ReaNINJAM" },
  { "reastream",                     "util",     "",           "fx",         "ReaStream" },
  { "reavocode",                     "pitch",    "",           "fx",         "ReaVocode" },
  { "reelbus 4",                     "tape",     "",           "fx",         "ReelBus 4" },
  { "reference",                     "util",     "",           "fx",         "REFERENCE" },
  { "resonator",                     "filter",   "",           "fx",         "Resonator" },
  { "scheps 73",                     "eq",       "",           "fx",         "Scheps 73" },
  { "sforzando",                     "sampler",  "",           "instrument", "sforzando" },
  { "sibilance",                     "de-ess",   "",           "fx",         "Sibilance" },
  { "snap heap",                     "util",     "",           "fx",         "Snap Heap" },
  { "super vhs",                     "tape",     "",           "fx",         "Super VHS" },
  { "t racks 5",                     "strip",    "",           "fx",         "T-RackS 5" },
  { "the giant",                     "keys",     "",           "instrument", "The Giant" },
  { "uad la 2a",                     "comp",     "",           "fx",         "UAD LA-2A" },
  { "una corda",                     "keys",     "",           "instrument", "Una Corda" },
  { "undulator",                     "mod",      "",           "fx",         "Undulator" },
  { "volcano 3",                     "filter",   "",           "fx",         "Volcano 3" },
  { "waves geq",                     "eq",       "",           "fx",         "Waves GEQ" },
  { "weiss eq1",                     "eq",       "",           "fx",         "Weiss EQ1" },
  { "amp room",                      "amp",      "pedal",      "fx",         "Amp Room" },
  { "antresol",                      "mod",      "",           "fx",         "Antresol" },
  { "aparillo",                      "synth",    "",           "instrument", "Aparillo" },
  { "api 2500",                      "comp",     "",           "fx",         "API 2500" },
  { "ashlight",                      "sfx",      "",           "instrument", "Ashlight" },
  { "backbone",                      "drums",    "",           "instrument", "Backbone" },
  { "black 76",                      "comp",     "fet",        "fx",         "Black 76" },
  { "blue iii",                      "synth",    "",           "instrument", "BLUE-III" },
  { "busterse",                      "comp",     "bus",        "fx",         "BUSTERse" },
  { "bx meter",                      "meter",    "loudness",   "fx",         "bx_meter" },
  { "bx rooms",                      "verb",     "room",       "fx",         "bx_rooMS" },
  { "cla epic",                      "verb",     "",           "fx",         "CLA Epic" },
  { "damage 2",                      "drums",    "",           "instrument", "Damage 2" },
  { "degrader",                      "sat",      "",           "fx",         "Degrader" },
  { "discord4",                      "pitch",    "",           "fx",         "Discord4" },
  { "dpmeter5",                      "meter",    "loudness",   "fx",         "dpMeter5" },
  { "drumazon",                      "drums",    "",           "instrument", "Drumazon" },
  { "echobode",                      "delay",    "",           "fx",         "Echobode" },
  { "elephant",                      "limit",    "",           "fx",         "Elephant" },
  { "emissary",                      "amp",      "",           "fx",         "Emissary" },
  { "ensemble",                      "mod",      "",           "fx",         "Ensemble" },
  { "ezkeys 2",                      "keys",     "",           "instrument", "EZkeys 2" },
  { "falcon 3",                      "sampler",  "",           "instrument", "Falcon 3" },
  { "galactic",                      "verb",     "",           "fx",         "Galactic" },
  { "glitch 2",                      "time",     "",           "fx",         "Glitch 2" },
  { "gullfoss",                      "eq",       "",           "fx",         "Gullfoss" },
  { "h reverb",                      "verb",     "",           "fx",         "H-Reverb" },
  { "halion 7",                      "sampler",  "",           "instrument", "HALion 7" },
  { "illusion",                      "verb",     "",           "fx",         "Illusion" },
  { "indent 2",                      "clip",     "",           "fx",         "Indent 2" },
  { "j37 tape",                      "tape",     "",           "fx",         "J37 Tape" },
  { "keyscape",                      "keys",     "",           "instrument", "Keyscape" },
  { "luftikus",                      "eq",       "",           "fx",         "Luftikus" },
  { "lush 101",                      "synth",    "",           "instrument", "LuSH-101" },
  { "maag eq4",                      "eq",       "",           "fx",         "Maag EQ4" },
  { "mcompare",                      "util",     "",           "fx",         "MCompare" },
  { "mdrummer",                      "drums",    "",           "instrument", "MDrummer" },
  { "megaverb",                      "verb",     "",           "fx",         "Megaverb" },
  { "molot ge",                      "comp",     "",           "fx",         "Molot GE" },
  { "mondomod",                      "mod",      "",           "fx",         "MondoMod" },
  { "movement",                      "mod",      "",           "fx",         "Movement" },
  { "multiply",                      "mod",      "",           "fx",         "Multiply" },
  { "mutility",                      "util",     "pan",        "fx",         "MUtility" },
  { "mvibrato",                      "mod",      "",           "fx",         "MVibrato" },
  { "mvmeter2",                      "meter",    "",           "fx",         "mvMeter2" },
  { "mysteria",                      "sfx",      "",           "instrument", "Mysteria" },
  { "nastyvcs",                      "strip",    "",           "fx",         "NastyVCS" },
  { "nectar 4",                      "pitch",    "",           "fx",         "Nectar 4" },
  { "nepheton",                      "drums",    "",           "instrument", "Nepheton" },
  { "nithonat",                      "drums",    "",           "instrument", "Nithonat" },
  { "ohmicide",                      "sat",      "",           "fx",         "Ohmicide" },
  { "phoscyon",                      "synth",    "",           "instrument", "Phoscyon" },
  { "pigments",                      "synth",    "",           "instrument", "Pigments" },
  { "pitchmap",                      "pitch",    "",           "fx",         "PITCHMAP" },
  { "podolski",                      "synth",    "",           "instrument", "Podolski" },
  { "polyplex",                      "drums",    "",           "instrument", "Polyplex" },
  { "punchbox",                      "drums",    "",           "instrument", "PunchBOX" },
  { "quanta 2",                      "synth",    "",           "instrument", "Quanta 2" },
  { "radiator",                      "sat",      "",           "fx",         "Radiator" },
  { "readelay",                      "delay",    "",           "fx",         "ReaDelay" },
  { "realimit",                      "limit",    "",           "fx",         "ReaLimit" },
  { "reapitch",                      "pitch",    "",           "fx",         "ReaPitch" },
  { "reavoice",                      "pitch",    "",           "fx",         "ReaVoice" },
  { "reaxcomp",                      "comp",     "",           "fx",         "ReaXcomp" },
  { "reel adt",                      "mod",      "",           "fx",         "Reel ADT" },
  { "rematrix",                      "verb",     "convolution", "fx",         "REmatrix" },
  { "rise hit",                      "sfx",      "",           "instrument", "Rise & Hit" },
  { "saturn 2",                      "sat",      "",           "fx",         "Saturn 2" },
  { "speedrum",                      "drums",    "",           "instrument", "Speedrum" },
  { "spitfish",                      "de-ess",   "",           "fx",         "Spitfish" },
  { "spl iron",                      "comp",     "",           "fx",         "SPL IRON" },
  { "stageone",                      "width",    "",           "fx",         "StageOne" },
  { "strike 2",                      "drums",    "",           "instrument", "Strike 2" },
  { "supertap",                      "delay",    "",           "fx",         "SuperTap" },
  { "surge xt",                      "synth",    "",           "instrument", "Surge XT" },
  { "sylenth1",                      "synth",    "",           "instrument", "Sylenth1" },
  { "tal drum",                      "drums",    "",           "instrument", "TAL-Drum" },
  { "tdr nova",                      "eq",       "",           "fx",         "TDR Nova" },
  { "the drop",                      "filter",   "",           "fx",         "The Drop" },
  { "the glue",                      "comp",     "bus",        "fx",         "The Glue" },
  { "trueiron",                      "sat",      "",           "fx",         "TrueIron" },
  { "tyrelln6",                      "synth",    "",           "instrument", "TyrellN6" },
  { "ultratap",                      "delay",    "",           "fx",         "UltraTap" },
  { "adclip7",                       "clip",     "",           "fx",         "ADClip7" },
  { "api 550",                       "eq",       "",           "fx",         "API 550" },
  { "api 560",                       "eq",       "",           "fx",         "API 560" },
  { "arousor",                       "comp",     "",           "fx",         "Arousor" },
  { "atlas 2",                       "drums",    "",           "instrument", "Atlas 2" },
  { "avenger",                       "synth",    "",           "instrument", "Avenger" },
  { "bigkick",                       "drums",    "",           "instrument", "BigKick" },
  { "brusfri",                       "util",     "",           "fx",         "Brusfri" },
  { "bx solo",                       "util",     "monitoring", "fx",         "bx_solo" },
  { "channev",                       "strip",    "",           "fx",         "Channev" },
  { "cp 70 v",                       "keys",     "",           "instrument", "CP-70 V" },
  { "cs 80 v",                       "synth",    "",           "instrument", "CS-80 V" },
  { "dbx 160",                       "comp",     "",           "fx",         "dbx 160" },
  { "density",                       "sat",      "",           "fx",         "Density" },
  { "doubler",                       "width",    "",           "fx",         "Doubler" },
  { "drumaxx",                       "drums",    "",           "instrument", "Drumaxx" },
  { "drumlab",                       "drums",    "",           "instrument", "DrumLab" },
  { "dyna mu",                       "comp",     "vari-mu",    "fx",         "Dyna-Mu" },
  { "echoboy",                       "delay",    "",           "fx",         "EchoBoy" },
  { "elevate",                       "limit",    "",           "fx",         "Elevate" },
  { "fg grey",                       "comp",     "bus",        "fx",         "FG-Grey" },
  { "glisseq",                       "eq",       "dynamic",    "fx",         "GlissEQ" },
  { "gravity",                       "sfx",      "",           "instrument", "Gravity" },
  { "h delay",                       "delay",    "",           "fx",         "H-Delay" },
  { "haaze 2",                       "width",    "",           "fx",         "Haaze 2" },
  { "inphase",                       "util",     "",           "fx",         "InPhase" },
  { "kclip 3",                       "clip",     "",           "fx",         "KClip 3" },
  { "lfotool",                       "mod",      "",           "fx",         "LFOTool" },
  { "loudmax",                       "limit",    "",           "fx",         "LoudMax" },
  { "massive",                       "synth",    "",           "instrument", "Massive" },
  { "morphit",                       "util",     "monitoring", "fx",         "Morphit" },
  { "neoverb",                       "verb",     "",           "fx",         "Neoverb" },
  { "nexus 4",                       "synth",    "",           "instrument", "Nexus 4" },
  { "nucleus",                       "orchestral", "",           "instrument", "Nucleus" },
  { "octavox",                       "pitch",    "",           "fx",         "Octavox" },
  { "permut8",                       "time",     "",           "fx",         "Permut8" },
  { "pha 979",                       "util",     "",           "fx",         "PHA-979" },
  { "polygon",                       "sfx",      "",           "instrument", "Polygon" },
  { "pro c 2",                       "comp",     "",           "fx",         "Pro-C 2" },
  { "pro l 2",                       "limit",    "",           "fx",         "Pro-L 2" },
  { "pro q 3",                       "eq",       "",           "fx",         "Pro-Q 3" },
  { "pro r 2",                       "verb",     "",           "fx",         "Pro-R 2" },
  { "punch 2",                       "drums",    "",           "instrument", "Punch-2" },
  { "reacast",                       "util",     "",           "fx",         "ReaCast" },
  { "reacomp",                       "comp",     "",           "fx",         "ReaComp" },
  { "reagate",                       "gate",     "",           "fx",         "ReaGate" },
  { "reatune",                       "pitch",    "",           "fx",         "ReaTune" },
  { "reaverb",                       "verb",     "",           "fx",         "ReaVerb" },
  { "repitch",                       "pitch",    "",           "fx",         "RePitch" },
  { "repro 5",                       "synth",    "",           "instrument", "Repro-5" },
  { "sga1566",                       "sat",      "tube",       "fx",         "SGA1566" },
  { "sigmund",                       "delay",    "",           "fx",         "Sigmund" },
  { "simplon",                       "filter",   "",           "fx",         "Simplon" },
  { "soothe2",                       "eq",       "",           "fx",         "soothe2" },
  { "spectre",                       "sat",      "",           "fx",         "Spectre" },
  { "spliteq",                       "eq",       "",           "fx",         "SplitEQ" },
  { "totape6",                       "tape",     "",           "fx",         "ToTape6" },
  { "trilian",                       "sampler",  "",           "instrument", "Trilian" },
  { "turbine",                       "sfx",      "",           "instrument", "Turbine" },
  { "vibrato",                       "mod",      "",           "fx",         "Vibrato" },
  { "vislm 2",                       "meter",    "loudness",   "fx",         "VisLM 2" },
  { "vocodex",                       "pitch",    "",           "fx",         "Vocodex" },
  { "vsr s24",                       "verb",     "",           "fx",         "VSR S24" },
  { "wurli v",                       "keys",     "",           "instrument", "Wurli V" },
  { "x noise",                       "util",     "",           "fx",         "X-Noise" },
  { "xpand 2",                       "sampler",  "",           "instrument", "Xpand!2" },
  { "z noise",                       "util",     "",           "fx",         "Z-Noise" },
  { "aether",                        "verb",     "",           "fx",         "Aether" },
  { "arcade",                        "sampler",  "",           "instrument", "Arcade" },
  { "boogex",                        "amp",      "cabinet",    "fx",         "Boogex" },
  { "center",                        "width",    "",           "fx",         "Center" },
  { "choral",                        "mod",      "",           "fx",         "Choral" },
  { "cla 2a",                        "comp",     "",           "fx",         "CLA-2A" },
  { "cla 3a",                        "comp",     "",           "fx",         "CLA-3A" },
  { "cycles",                        "sfx",      "",           "instrument", "Cycles" },
  { "driver",                        "sat",      "",           "fx",         "Driver" },
  { "dune 3",                        "synth",    "",           "instrument", "Dune 3" },
  { "enigma",                        "mod",      "",           "fx",         "Enigma" },
  { "evolve",                        "sfx",      "",           "instrument", "Evolve" },
  { "falcon",                        "sampler",  "",           "instrument", "Falcon" },
  { "fg 116",                        "comp",     "",           "fx",         "FG-116 (VMR)" },
  { "fg 401",                        "comp",     "",           "fx",         "FG-401" },
  { "fg red",                        "comp",     "",           "fx",         "FG-Red" },
  { "fg x 2",                        "limit",    "",           "fx",         "FG-X 2" },
  { "harmor",                        "synth",    "",           "instrument", "Harmor" },
  { "hive 2",                        "synth",    "",           "instrument", "Hive 2" },
  { "jaeger",                        "orchestral", "",           "instrument", "Jaeger" },
  { "kelvin",                        "sat",      "",           "fx",         "Kelvin" },
  { "kick 2",                        "drums",    "",           "instrument", "Kick 2" },
  { "levels",                        "meter",    "",           "fx",         "LEVELS" },
  { "mini v",                        "synth",    "",           "instrument", "Mini V" },
  { "ml4000",                        "limit",    "",           "fx",         "ML4000" },
  { "mtuner",                        "meter",    "spectrum",   "fx",         "MTuner" },
  { "nimbus",                        "verb",     "",           "fx",         "Nimbus" },
  { "odin 2",                        "synth",    "",           "instrument", "Odin 2" },
  { "panman",                        "mod",      "",           "fx",         "PanMan" },
  { "phasis",                        "mod",      "",           "fx",         "Phasis" },
  { "portal",                        "time",     "",           "fx",         "Portal" },
  { "powair",                        "comp",     "",           "fx",         "POWAIR" },
  { "pro ds",                        "de-ess",   "",           "fx",         "Pro-DS" },
  { "pro mb",                        "comp",     "",           "fx",         "Pro-MB" },
  { "psp 42",                        "delay",    "",           "fx",         "PSP 42" },
  { "pteq x",                        "eq",       "",           "fx",         "PTEq-X" },
  { "reafir",                        "eq",       "",           "fx",         "ReaFir" },
  { "s gear",                        "amp",      "",           "fx",         "S-Gear" },
  { "satson",                        "sat",      "",           "fx",         "Satson" },
  { "schope",                        "meter",    "spectrum",   "fx",         "Schope" },
  { "sitala",                        "drums",    "",           "instrument", "Sitala" },
  { "sp2016",                        "verb",     "",           "fx",         "SP2016" },
  { "synth1",                        "synth",    "",           "instrument", "Synth1" },
  { "sytrus",                        "synth",    "",           "instrument", "Sytrus" },
  { "thrill",                        "sfx",      "",           "instrument", "Thrill" },
  { "type a",                        "sat",      "",           "fx",         "Type A" },
  { "unveil",                        "util",     "",           "fx",         "UNVEIL" },
  { "vb3 ii",                        "keys",     "",           "instrument", "VB3-II" },
  { "zebra2",                        "synth",    "",           "instrument", "Zebra2" },
  { "aalto",                         "synth",    "",           "instrument", "Aalto" },
  { "ab lm",                         "util",     "",           "fx",         "AB_LM" },
  { "b 3 v",                         "keys",     "",           "instrument", "B-3 V" },
  { "bloom",                         "eq",       "",           "fx",         "bloom" },
  { "blue3",                         "keys",     "",           "instrument", "Blue3" },
  { "cmi v",                         "sampler",  "",           "instrument", "CMI V" },
  { "dc8c3",                         "comp",     "",           "fx",         "DC8C3" },
  { "de555",                         "de-ess",   "",           "fx",         "DE555" },
  { "deess",                         "de-ess",   "",           "fx",         "DeEss" },
  { "dexed",                         "synth",    "",           "instrument", "Dexed" },
  { "dseq3",                         "eq",       "dynamic",    "fx",         "DSEQ3" },
  { "eos 2",                         "verb",     "",           "fx",         "Eos 2" },
  { "fg 2a",                         "comp",     "",           "fx",         "FG-2A" },
  { "fg 73",                         "strip",    "",           "fx",         "FG-73" },
  { "fg mu",                         "comp",     "vari-mu",    "fx",         "FG-Mu" },
  { "flair",                         "mod",      "",           "fx",         "Flair" },
  { "freak",                         "mod",      "",           "fx",         "Freak" },
  { "gclip",                         "clip",     "",           "fx",         "GClip" },
  { "gsnap",                         "pitch",    "",           "fx",         "GSnap" },
  { "gtune",                         "meter",    "spectrum",   "fx",         "GTune" },
  { "gypsy",                         "world",    "",           "instrument", "Gypsy" },
  { "hypha",                         "sfx",      "",           "instrument", "Hypha" },
  { "isl 2",                         "limit",    "",           "fx",         "ISL 2" },
  { "isol8",                         "util",     "monitoring", "fx",         "ISOL8" },
  { "krush",                         "sat",      "",           "fx",         "Krush" },
  { "lx480",                         "verb",     "",           "fx",         "LX480" },
  { "museq",                         "eq",       "",           "fx",         "museq" },
  { "nadir",                         "amp",      "cabinet",    "fx",         "NadIR" },
  { "nerve",                         "drums",    "",           "instrument", "Nerve" },
  { "nexus",                         "synth",    "",           "instrument", "Nexus" },
  { "noire",                         "keys",     "",           "instrument", "Noire" },
  { "ob xd",                         "synth",    "",           "instrument", "OB-Xd" },
  { "pg 8x",                         "synth",    "",           "instrument", "PG-8X" },
  { "pro g",                         "comp",     "",           "fx",         "Pro-G" },
  { "rbass",                         "bass",     "",           "fx",         "RBass" },
  { "rc 24",                         "verb",     "",           "fx",         "RC 24" },
  { "rc 48",                         "verb",     "",           "fx",         "RC 48" },
  { "rcomp",                         "comp",     "",           "fx",         "RComp" },
  { "reaeq",                         "eq",       "",           "fx",         "ReaEQ" },
  { "reels",                         "tape",     "",           "fx",         "Reels" },
  { "rverb",                         "verb",     "",           "fx",         "RVerb" },
  { "satin",                         "tape",     "",           "fx",         "Satin" },
  { "serum",                         "synth",    "",           "instrument", "Serum" },
  { "sie q",                         "eq",       "",           "fx",         "Sie-Q" },
  { "skaka",                         "drums",    "",           "instrument", "Skaka" },
  { "soneq",                         "eq",       "",           "fx",         "SonEQ" },
  { "spiff",                         "comp",     "",           "fx",         "spiff" },
  { "spire",                         "synth",    "",           "instrument", "Spire" },
  { "stilt",                         "eq",       "tilt",       "fx",         "sTilt" },
  { "teote",                         "eq",       "",           "fx",         "TEOTE" },
  { "thorn",                         "synth",    "",           "instrument", "Thorn" },
  { "trash",                         "sat",      "",           "fx",         "Trash" },
  { "tverb",                         "verb",     "",           "fx",         "Tverb" },
  { "ubk 1",                         "comp",     "",           "fx",         "UBK-1" },
  { "vinyl",                         "tape",     "",           "fx",         "Vinyl" },
  { "vital",                         "synth",    "",           "instrument", "Vital" },
  { "wider",                         "width",    "",           "fx",         "Wider" },
  { "xenon",                         "limit",    "",           "fx",         "Xenon" },
  { "ba 1",                          "synth",    "",           "instrument", "BA-1" },
  { "bfd3",                          "drums",    "",           "instrument", "BFD3" },
  { "bite",                          "sat",      "",           "fx",         "Bite" },
  { "boom",                          "drums",    "",           "instrument", "Boom" },
  { "dc1a",                          "comp",     "",           "fx",         "DC1A" },
  { "diva",                          "synth",    "",           "instrument", "Diva" },
  { "dust",                          "sfx",      "",           "instrument", "Dust" },
  { "helm",                          "synth",    "",           "instrument", "Helm" },
  { "hg 2",                          "sat",      "",           "fx",         "HG-2" },
  { "ivgi",                          "sat",      "",           "fx",         "IVGI" },
  { "labs",                          "sampler",  "",           "instrument", "LABS" },
  { "lala",                          "comp",     "opto",       "fx",         "LALA" },
  { "life",                          "drums",    "",           "instrument", "Life" },
  { "lisp",                          "de-ess",   "",           "fx",         "Lisp" },
  { "lohi",                          "sat",      "",           "fx",         "Lohi" },
  { "mjuc",                          "comp",     "",           "fx",         "MJUC" },
  { "msed",                          "util",     "",           "fx",         "MSED" },
  { "opus",                          "sampler",  "",           "instrument", "Opus" },
  { "rare",                          "eq",       "",           "fx",         "Rare" },
  { "raum",                          "verb",     "",           "fx",         "Raum" },
  { "reeq",                          "eq",       "",           "fx",         "ReEQ (JSFX)" },
  { "rvox",                          "comp",     "",           "fx",         "RVox" },
  { "sdrr",                          "sat",      "",           "fx",         "SDRR" },
  { "silk",                          "world",    "",           "instrument", "Silk" },
  { "silo",                          "verb",     "",           "fx",         "SILO" },
  { "span",                          "meter",    "",           "fx",         "SPAN" },
  { "ssd5",                          "drums",    "",           "instrument", "SSD5" },
  { "taip",                          "tape",     "",           "fx",         "TAIP" },
  { "tape",                          "tape",     "",           "fx",         "Tape" },
  { "th u",                          "amp",      "cabinet",    "fx",         "TH-U" },
  { "wow2",                          "filter",   "",           "fx",         "WOW2" },
  { "fm8",                           "synth",    "",           "instrument", "FM8" },
  { "mv2",                           "comp",     "",           "fx",         "MV2" },
  { "ott",                           "comp",     "",           "fx",         "OTT" },
  { "req",                           "eq",       "",           "fx",         "REQ" },
  { "rev",                           "sfx",      "",           "instrument", "REV" },
  { "l2",                            "limit",    "",           "fx",         "L2" },
  { "m1",                            "synth",    "",           "instrument", "M1" },
  { "pi",                            "util",     "",           "fx",         "Pi" },
  { "ra",                            "world",    "",           "instrument", "RA" },
  { "xo",                            "drums",    "",           "instrument", "XO" },
}

-- [lowercased ident] = { bucket, subcategory, kind }
M.PATHS = {
  ["chmaha airwindows jsfx ports/consoles/cora.jsfx"] = { "summing", "", "fx" },
  ["chmaha airwindows jsfx ports/consoles/octo4bus.jsfx"] = { "summing", "bus", "fx" },
  ["chmaha airwindows jsfx ports/consoles/octo4channel.jsfx"] = { "summing", "channel", "fx" },
  ["chmaha airwindows jsfx ports/consoles/seattlety.jsfx"] = { "summing", "", "fx" },
  ["chmaha airwindows jsfx ports/dithers/groovydither.jsfx"] = { "util", "dither", "fx" },
  ["chmaha airwindows jsfx ports/dithers/piratedither.jsfx"] = { "util", "dither", "fx" },
  ["chmaha airwindows jsfx ports/dithers/wtfdither.jsfx"] = { "util", "dither", "fx" },
  ["chmaha airwindows jsfx ports/various/channeltwister.jsfx"] = { "util", "routing", "fx" },
  ["chmaha airwindows jsfx ports/various/convolvulus.jsfx"] = { "width", "", "fx" },
  ["chmaha airwindows jsfx ports/various/edgefilter.jsfx"] = { "filter", "", "fx" },
  ["chmaha airwindows jsfx ports/various/elemental.jsfx"] = { "strip", "", "fx" },
  ["chmaha airwindows jsfx ports/various/enyo.jsfx"] = { "util", "generator", "fx" },
  ["chmaha airwindows jsfx ports/various/groovelens.jsfx"] = { "util", "generator", "fx" },
  ["chmaha airwindows jsfx ports/various/groovelens2.jsfx"] = { "util", "generator", "fx" },
  ["chmaha airwindows jsfx ports/various/ignis.jsfx"] = { "sat", "", "fx" },
  ["chmaha airwindows jsfx ports/various/nogginknock.jsfx"] = { "bass", "", "fx" },
  ["chmaha airwindows jsfx ports/various/quantumpan.jsfx"] = { "util", "pan", "fx" },
  ["chmaha airwindows jsfx ports/various/stratos.jsfx"] = { "eq", "", "fx" },
  ["chmaha airwindows jsfx ports/various/velveteq.jsfx"] = { "eq", "", "fx" },
  ["chmaha airwindows jsfx ports/various/widealchemy.jsfx"] = { "width", "", "fx" },
  ["d jsfx/1175 d.jsfx"] = { "comp", "fet", "fx" },
  ["d jsfx/fairlychildish d.jsfx"] = { "comp", "vari-mu", "fx" },
  ["d jsfx/la-2kan d.jsfx"] = { "comp", "opto", "fx" },
  ["d jsfx/quickdelay d.jsfx"] = { "delay", "", "fx" },
  ["d jsfx/rc inflator d.jsfx"] = { "sat", "", "fx" },
  ["d jsfx/slax d.jsfx"] = { "comp", "opto", "fx" },
  ["d jsfx/thunderkick d.jsfx"] = { "bass", "", "fx" },
  ["d jsfx/transpire d.jsfx"] = { "util", "transient", "fx" },
  ["docshadrach fxs/effects/speaker_soul_engine.jsfx"] = { "sat", "", "fx" },
  ["docshadrach fxs/effects/spectral_harshness_control.jsfx"] = { "eq", "dynamic", "fx" },
  ["docshadrach fxs/effects/the_analog_molecule.jsfx"] = { "summing", "bus", "fx" },
  ["docshadrach fxs/effects/the_depth_control.jsfx"] = { "verb", "", "fx" },
  ["docshadrach fxs/effects/the_hot_summer.jsfx"] = { "summing", "bus", "fx" },
  ["docshadrach fxs/utilities/levelmatch_core.jsfx"] = { "util", "monitoring", "fx" },
  ["docshadrach fxs/utilities/nam_alignment_tool.jsfx"] = { "util", "", "fx" },
  ["docshadrach fxs/utilities/v-clamp.jsfx"] = { "util", "", "fx" },
  ["eon_reakit_bundle/eon/eon_jsfx/fx/ddc_reakit.jsfx"] = { "comp", "", "fx" },
  ["eon_reakit_bundle/eon/eon_jsfx/fx/expressbus_reakit.jsfx"] = { "comp", "bus", "fx" },
  ["eon_reakit_bundle/eon/eon_jsfx/fx/spice.jsfx"] = { "summing", "", "fx" },
  ["eon_reakit_bundle/eon/eon_jsfx/midi/midinoterepeater_reakit.jsfx"] = { "midi", "", "midi" },
  ["eon_reakit_bundle/installer/src/swing lite/swing_lite.jsfx"] = { "drums", "", "instrument" },
  ["eon_reakit_bundle/installer/src/swing/eon_fx_return_view.jsfx"] = { "meter", "", "fx" },
  ["eon_reakit_bundle/installer/src/swing/eon_lens.jsfx"] = { "util", "", "fx" },
  ["eon_reakit_bundle/installer/src/swing/eon_stepseq.jsfx"] = { "midi", "", "midi" },
  ["eon_reakit_bundle/installer/src/swing/swing_reakit.jsfx"] = { "drums", "", "instrument" },
  ["leandro facchinetti/programming audio effects/leafac_broken white noise.jsfx"] = { "util", "generator", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_burn-in speakers.jsfx"] = { "util", "generator", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_copy channel to all channels.jsfx"] = { "util", "routing", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_copy left to right.jsfx"] = { "util", "routing", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_copy right to left.jsfx"] = { "util", "routing", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_dc offset.jsfx"] = { "util", "", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_enveloper.jsfx"] = { "util", "", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_mute.jsfx"] = { "util", "", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_null tester.jsfx"] = { "util", "null-test", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_oscilloscope.jsfx"] = { "meter", "", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_rectifier full-wave.jsfx"] = { "sat", "", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_rectifier half-wave.jsfx"] = { "sat", "", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_rms.jsfx"] = { "meter", "", "fx" },
  ["leandro facchinetti/programming audio effects/leafac_white noise.jsfx"] = { "util", "generator", "fx" },
  ["leandro facchinetti/utility/leafac_automixer.jsfx"] = { "util", "automix", "fx" },
  ["leandro facchinetti/utility/leafac_waveform/leafac_waveform.jsfx"] = { "meter", "", "fx" },
  ["lms plugins/drumbanger/lms_drumbanger.jsfx"] = { "drums", "", "instrument" },
  ["lms plugins/lms/lms_area51_v2.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/lms_bottom_feeder_v2.jsfx"] = { "amp", "", "fx" },
  ["lms plugins/lms/lms_drone_voice.jsfx"] = { "util", "generator", "midi" },
  ["lms plugins/lms/lms_drum_trigger.jsfx"] = { "util", "transient", "midi" },
  ["lms plugins/lms/lms_drumbanger.jsfx"] = { "drums", "", "instrument" },
  ["lms plugins/lms/lms_faker.jsfx"] = { "pitch", "", "fx" },
  ["lms plugins/lms/lms_frenchie_v2.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/lms_fridge_v2.jsfx"] = { "amp", "bass", "fx" },
  ["lms plugins/lms/lms_henge_on_crack.jsfx"] = { "delay", "tape", "fx" },
  ["lms plugins/lms/lms_lil_stinker.jsfx"] = { "synth", "", "instrument" },
  ["lms plugins/lms/lms_mega_increasinator.jsfx"] = { "limit", "", "fx" },
  ["lms plugins/lms/lms_nightmare_v2.jsfx"] = { "amp", "bass", "fx" },
  ["lms plugins/lms/lms_nuug420.jsfx"] = { "synth", "", "instrument" },
  ["lms plugins/lms/lms_oj95_v2.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/lms_ol_reliable_v2.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/lms_piece_of_shit.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/lms_punk_idol_v2.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/lms_rtw.jsfx"] = { "strip", "", "fx" },
  ["lms plugins/lms/lms_silver69.jsfx"] = { "comp", "opto", "fx" },
  ["lms plugins/lms/lms_tomasteknik_v2.jsfx"] = { "amp", "bass", "fx" },
  ["lms plugins/lms/lms_traumatizer.jsfx"] = { "comp", "", "fx" },
  ["lms plugins/lms/lms_trsob_v2.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/lms_twins_v2.jsfx"] = { "amp", "guitar", "fx" },
  ["lms plugins/lms/scripts/lms_drone_voice.jsfx"] = { "util", "generator", "midi" },
  ["loser/50hzkicker"] = { "bass", "", "fx" },
  ["loser/centercanceler"] = { "width", "", "fx" },
  ["loser/midi_eq_ducker"] = { "eq", "", "fx" },
  ["loser/ppp"] = { "mod", "", "fx" },
  ["loser/timedifferencepan"] = { "width", "", "fx" },
  ["mrelwood/hamles 3/mrelwood_hamles_3_for_collab3"] = { "mod", "", "fx" },
  ["mrelwood/mrelwood_bamp_0v90/bamp beta 0v91"] = { "amp", "bass", "fx" },
  ["mrelwood/mrelwood_bandbass_0v02"] = { "comp", "", "fx" },
  ["mrelwood/mrelwood_blipper_blip_generator"] = { "util", "generator", "fx" },
  ["mrelwood/mrelwood_desser"] = { "de-ess", "", "fx" },
  ["mrelwood/mrelwood_dubstep_wob-wob"] = { "filter", "", "fx" },
  ["mrelwood/mrelwood_dynastrip_beta"] = { "strip", "", "fx" },
  ["mrelwood/mrelwood_fade"] = { "util", "fade", "fx" },
  ["mrelwood/mrelwood_frigate_0v2"] = { "gate", "", "fx" },
  ["mrelwood/mrelwood_glitchpress 1v05"] = { "util", "", "fx" },
  ["mrelwood/mrelwood_goldcomp4"] = { "comp", "opto", "fx" },
  ["mrelwood/mrelwood_kickbass_0v35"] = { "comp", "", "fx" },
  ["mrelwood/mrelwood_metronoptics"] = { "util", "metronome", "fx" },
  ["mrelwood/mrelwood_midi_cc-pc_mapper"] = { "util", "", "midi" },
  ["mrelwood/mrelwood_midi_cc_mute"] = { "util", "", "midi" },
  ["mrelwood/mrelwood_midi_humanator"] = { "util", "", "midi" },
  ["mrelwood/mrelwood_midi_mute"] = { "util", "", "midi" },
  ["mrelwood/mrelwood_midi_transpose-mix 2"] = { "util", "", "midi" },
  ["mrelwood/mrelwood_mothercomp_1v18"] = { "comp", "", "fx" },
  ["mrelwood/mrelwood_multicomp_beta"] = { "comp", "multiband", "fx" },
  ["mrelwood/mrelwood_multimix_beta"] = { "util", "", "fx" },
  ["mrelwood/mrelwood_noisecheck"] = { "meter", "", "fx" },
  ["mrelwood/mrelwood_pandelay"] = { "width", "", "fx" },
  ["mrelwood/mrelwood_routter"] = { "util", "routing", "fx" },
  ["mrelwood/mrelwood_sineseeker_0v3"] = { "util", "generator", "fx" },
  ["mrelwood/mrelwood_sinesweeper_2"] = { "util", "generator", "fx" },
  ["mrelwood/mrelwood_sky_2v05"] = { "limit", "", "fx" },
  ["mrelwood/mrelwood_sonnycomp_1v06"] = { "comp", "", "fx" },
  ["mrelwood/mrelwood_synctremolo_0v4"] = { "mod", "", "fx" },
  ["mrelwood/mrelwood_vocastrip_plus_beta"] = { "strip", "", "fx" },
  ["mrelwood/mrelwood_vochorus"] = { "mod", "", "fx" },
  ["mxr flanger/doubler"] = { "mod", "", "fx" },
  ["reateam jsfx/distortion/rcinflator2_ideal.jsfx"] = { "sat", "", "fx" },
  ["reateam jsfx/distortion/rcinflator2_oxford.jsfx"] = { "sat", "", "fx" },
  ["reateam jsfx/distortion/rcjach_rcinflator.jsfx"] = { "sat", "", "fx" },
  ["reateam jsfx/distortion/tiar_ze morpho dist.jsfx"] = { "sat", "", "fx" },
  ["reateam jsfx/dynamic/mrelwood_bandbass.jsfx"] = { "comp", "", "fx" },
  ["reateam jsfx/filter/tilr_quickfilter.jsfx"] = { "filter", "", "fx" },
  ["reateam jsfx/filter/tilr_skfilter.jsfx"] = { "filter", "", "fx" },
  ["reateam jsfx/midi/albthealbatross_midi channel cycler.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/albthealbatross_midi chord strummer.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/albthealbatross_multi-channel midi timing randomizer.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/amagalma_midi keyboard split route transpose.jsfx"] = { "util", "crossover", "midi" },
  ["reateam jsfx/midi/bertbouwhuis_midi controller for s8 looper with fade in and out.jsfx"] = { "util", "fade", "midi" },
  ["reateam jsfx/midi/bor-t_midi_xy_pad_controller.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/boreg_midi routing matrix.jsfx"] = { "util", "routing", "midi" },
  ["reateam jsfx/midi/cfillion_midi note length control.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/cfillion_midi taps repeater.jsfx"] = { "delay", "", "midi" },
  ["reateam jsfx/midi/cfillion_note duplicator.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/ee33_triggered random modal riffer.jsfx"] = { "util", "generator", "midi" },
  ["reateam jsfx/midi/eralumin_midi channel toggle.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/erantalmor_midi rhythm trainer.jsfx"] = { "meter", "", "midi" },
  ["reateam jsfx/midi/gofer_poly aftertouch converter.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/juan_r_midi fret and pick.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mathphreak_learningbaby.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mb_midi event filter.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mb_reautomate.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mbncp_legato control.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnell_midi cc fluctuation.jsfx"] = { "util", "fade", "midi" },
  ["reateam jsfx/midi/mschnell_midi glissando.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnell_midi mpe to single channel.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnell_midi pb x x.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnell_midi route via gmem.jsfx"] = { "util", "routing", "midi" },
  ["reateam jsfx/midi/mschnell_midi slider and midi cc.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnell_note on velocity tool.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnell_slider to midi nrpm.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnell_xy pad.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/mschnellsid_xy pad x.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/polgo_midi envelocity.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/polgo_midi varocity.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/rekseffeks_midi cc to pitchbend.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/talagan_midi cc bistate button.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/talagan_midi cc mapper x.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/talagan_midi channel matrix router.jsfx"] = { "util", "routing", "midi" },
  ["reateam jsfx/midi/talagan_midi delay x.jsfx"] = { "delay", "", "midi" },
  ["reateam jsfx/midi/talagan_midi force notes to range.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/talagan_midi multi channel pre-delay live flagger.jsfx"] = { "delay", "", "midi" },
  ["reateam jsfx/midi/talagan_midi multi channel pre-delay.jsfx"] = { "delay", "", "midi" },
  ["reateam jsfx/midi/talagan_midi note remapper.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/talagan_midi poly aftertouch cc multiplexer.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/talagan_midi split pitch bend to ccs.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/tilr_notes to cc.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/tja_midi note-banked cc multiplier.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/tja_midi performer2.jsfx"] = { "util", "routing", "midi" },
  ["reateam jsfx/midi/tomaszpio_akai apc mini grid toggle.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/tomaszpio_apc pad blinker (sync to transport).jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/tomaszpio_midi hold notes range.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/urtzurd_midi glissando.jsfx"] = { "util", "generator", "midi" },
  ["reateam jsfx/midi/willdevelop_every_note_the_same.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/willdevelop_midi every note the same.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/willdevelop_midi note repeater [default key map b1 - a4].jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/willdevelop_midi velocity filter.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/xq_drum converter.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/midi/xq_drum deviator.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/misc/brumbear_livebeatrepeater.jsfx"] = { "time", "", "fx" },
  ["reateam jsfx/misc/brumbear_livescrubberducky.jsfx"] = { "time", "", "fx" },
  ["reateam jsfx/misc/tiar_pm_resynth.jsfx"] = { "pitch", "", "fx" },
  ["reateam jsfx/routing/mdf_51 to dms.jsfx"] = { "util", "channel-format", "fx" },
  ["reateam jsfx/routing/mdf_dms to 51.jsfx"] = { "util", "routing", "fx" },
  ["reateam jsfx/routing/mdf_dms to foa.jsfx"] = { "util", "channel-format", "fx" },
  ["reateam jsfx/routing/mdf_dms to quad.jsfx"] = { "util", "routing", "fx" },
  ["reateam jsfx/routing/mdf_foa to dms.jsfx"] = { "util", "channel-format", "fx" },
  ["reateam jsfx/routing/mdf_quad to dms.jsfx"] = { "util", "routing", "fx" },
  ["reateam jsfx/routing/mrelwood_routter.jsfx"] = { "util", "routing", "fx" },
  ["reateam jsfx/routing/mschnell_midi_route_note_on.jsfx"] = { "util", "routing", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 audio-midi.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 envgen.jsfx"] = { "util", "generator", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 envmultitool.jsfx"] = { "util", "generator", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 keyfollower.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 midimixer.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 nonlinearizer.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 oscillator-additive.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 oscillator-noise.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 oscillator-trapezoidal.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 oscillator-twinsaw.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 sampleandhold.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/synth/rearack modular synth/timewaster_rearack2 trigger.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/synth/tiar_2op pm synth.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tiar_chua oscillator.jsfx"] = { "sfx", "", "instrument" },
  ["reateam jsfx/synth/tiar_complex x filter synth.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tiar_shepard paradoxical synth.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tiar_ze cheesy harmonic synth.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tiar_ze digitharmorgan.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tiar_ze musette organ.jsfx"] = { "keys", "", "instrument" },
  ["reateam jsfx/synth/tilr_js3osc.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tilr_jsadditiv.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tilr_jsdrumpad.jsfx"] = { "drums", "", "instrument" },
  ["reateam jsfx/synth/tilr_jsdrumsynth.jsfx"] = { "drums", "", "instrument" },
  ["reateam jsfx/synth/tilr_jsmodulator.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/synth/tilr_jswavesynth.jsfx"] = { "synth", "", "instrument" },
  ["reateam jsfx/utility/az_automute.jsfx"] = { "util", "", "fx" },
  ["reateam jsfx/utility/coreyscogin_automixer.jsfx"] = { "util", "automix", "fx" },
  ["reateam jsfx/utility/jcgurango_midi arranged looper.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/utility/jcgurango_pre-arranged looper.jsfx"] = { "util", "", "fx" },
  ["reateam jsfx/utility/jsh_inline input viewer (mcp embedded).jsfx"] = { "meter", "", "fx" },
  ["reateam jsfx/utility/jw_gfxscope-beat-retrigger.jsfx"] = { "meter", "", "fx" },
  ["reateam jsfx/utility/mrelwood_blipper.jsfx"] = { "util", "generator", "fx" },
  ["reateam jsfx/utility/mschnell_midi auto engage.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/utility/mschnell_midi cc table.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/utility/mschnell_midi cc2sysex.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/utility/mschnell_midi convert to cc.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/utility/mschnell_midi display 3 ccs.jsfx"] = { "meter", "", "midi" },
  ["reateam jsfx/utility/mschnell_midi display patch name.jsfx"] = { "meter", "", "midi" },
  ["reateam jsfx/utility/mschnell_midi fade.jsfx"] = { "util", "fade", "midi" },
  ["reateam jsfx/utility/mschnell_midi trigger cc.jsfx"] = { "util", "generator", "midi" },
  ["reateam jsfx/utility/mschnell_midi volume control.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/utility/mschnell_multi_sin_generator.jsfx"] = { "util", "generator", "fx" },
  ["reateam jsfx/utility/mschnell_mute monitor when recording.jsfx"] = { "util", "monitoring", "fx" },
  ["reateam jsfx/utility/mschnell_slider to midi ps.jsfx"] = { "util", "", "midi" },
  ["reateam jsfx/utility/reaperblog_-12db dim.jsfx"] = { "util", "monitoring", "fx" },
  ["reateam jsfx/utility/timewaster midi-mouse.jsfx"] = { "util", "", "midi" },
  ["saike tools/amaranth/amaranth.jsfx"] = { "sampler", "", "instrument" },
  ["saike tools/basics/bandjoiner.jsfx"] = { "util", "crossover", "fx" },
  ["saike tools/basics/bandsplitter.jsfx"] = { "util", "crossover", "fx" },
  ["saike tools/basics/saike_never_odd_or_even.jsfx"] = { "sat", "", "fx" },
  ["saike tools/basics/saike_smooth.jsfx"] = { "sat", "", "fx" },
  ["saike tools/basics/tonestacks.jsfx"] = { "eq", "", "fx" },
  ["saike tools/basics/transience.jsfx"] = { "util", "transient", "fx" },
  ["saike tools/bric-a-brac/saike_bric_a_brac.jsfx"] = { "util", "", "fx" },
  ["saike tools/filther/filther.jsfx"] = { "filter", "", "fx" },
  ["saike tools/finalboss/saike_final_boss.jsfx"] = { "sat", "", "fx" },
  ["saike tools/modizer/modizer.jsfx"] = { "clip", "bitcrush", "fx" },
  ["saike tools/nuker/saike_nuker.jsfx"] = { "sat", "", "fx" },
  ["saike tools/partials/saike_partials.jsfx"] = { "filter", "", "fx" },
  ["saike tools/poprocks/poprocks.jsfx"] = { "sfx", "", "instrument" },
  ["saike tools/protosynth/saike_protosynth.jsfx"] = { "synth", "", "instrument" },
  ["saike tools/ravager/ravager_mb.jsfx"] = { "comp", "multiband", "fx" },
  ["saike tools/reabee/reabee.jsfx"] = { "mod", "", "fx" },
  ["saike tools/reflectosaurus/reflectosaurus.jsfx"] = { "delay", "", "fx" },
  ["saike tools/ripple/ripple.jsfx"] = { "util", "", "midi" },
  ["saike tools/saike_midi_arp/saike_midi_arp.jsfx"] = { "util", "", "midi" },
  ["saike tools/saikedrums/saikedrums.jsfx"] = { "drums", "", "instrument" },
  ["saike tools/sequencedfx/sequencedfx.jsfx"] = { "time", "", "fx" },
  ["saike tools/squashman/squashman.jsfx"] = { "sat", "", "fx" },
  ["saike tools/swellotron/swellotron.jsfx"] = { "verb", "convolution", "fx" },
  ["saike tools/yutani/saike_yutani.jsfx"] = { "synth", "", "instrument" },
  ["scarbee clavinet/pianet"] = { "keys", "", "instrument" },
  ["tukan/abxnull s2 (tukan)"] = { "util", "null-test", "fx" },
  ["tukan/ac trem (tukan)"] = { "mod", "", "fx" },
  ["tukan/blue lexikan s2 (tukan)"] = { "verb", "", "fx" },
  ["tukan/december synth (tukan)"] = { "synth", "", "instrument" },
  ["tukan/degrader s2 (tukan)"] = { "clip", "", "fx" },
  ["tukan/dis-treasure (tukan)"] = { "comp", "", "fx" },
  ["tukan/envelope (tukan)"] = { "util", "transient", "fx" },
  ["tukan/expgate 2 (tukan)"] = { "gate", "", "fx" },
  ["tukan/inline channel s2 (tukan)"] = { "strip", "", "fx" },
  ["tukan/inline remote s2 (tukan)"] = { "util", "", "fx" },
  ["tukan/la-1a (tukan)"] = { "comp", "opto", "fx" },
  ["tukan/la-2kan s2 (tukan)"] = { "comp", "opto", "fx" },
  ["tukan/lexikan (tukan)"] = { "verb", "", "fx" },
  ["tukan/lexikan 2 (tukan)"] = { "verb", "room", "fx" },
  ["tukan/midi arpeggiator (tukan)"] = { "util", "", "midi" },
  ["tukan/multiband processor (tukan)"] = { "comp", "multiband", "fx" },
  ["tukan/multiband processor s2 (tukan studios)"] = { "comp", "multiband", "fx" },
  ["tukan/nc76 (tukan)"] = { "comp", "fet", "fx" },
  ["tukan/nc76 s2 (tukan)"] = { "comp", "fet", "fx" },
  ["tukan/nc76b (tukan)"] = { "comp", "fet", "fx" },
  ["tukan/new treasure s2 (tukan)"] = { "comp", "", "fx" },
  ["tukan/pads (tukan)"] = { "drums", "", "instrument" },
  ["tukan/peak needle (tukan)"] = { "meter", "spectrum", "fx" },
  ["tukan/poly 24 (tukan)"] = { "synth", "", "instrument" },
  ["tukan/red lexikan s2 (tukan)"] = { "verb", "", "fx" },
  ["tukan/sequence (tukan)"] = { "util", "", "midi" },
  ["tukan/sphinx (tukan)"] = { "eq", "", "fx" },
  ["tukan/sphinx s2 (tukan)"] = { "util", "rider", "fx" },
  ["tukan/sumchannel (tukan)"] = { "strip", "", "fx" },
  ["tukan/sumchannel s2 (tukan)"] = { "strip", "", "fx" },
  ["tukan/sumthing (tukan)"] = { "summing", "bus", "fx" },
  ["tukan/sumthing si (tukan)"] = { "summing", "", "fx" },
  ["tukan/tookan poly-g (tukan)"] = { "synth", "", "instrument" },
  ["tukan/tool (tukan)"] = { "util", "routing", "fx" },
  ["tukan/tool s2 (tukan)"] = { "util", "routing", "fx" },
  ["tukan/violet envelope shaper s2 (tukan)"] = { "util", "transient", "fx" },
  ["tukan/wtfm synth (tukan)"] = { "synth", "", "instrument" },
}

return M
